eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
server:
  port: 10011
spring:
  application:
    name: console-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.10.163:3306/digital_mall?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: Zhanjian_123
  data:
    elasticsearch:
      cluster-name: aliyun-es
      cluster-nodes: 47.93.10.163:9300