eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
server:
  port: 10010
spring:
  application:
    name: console-controller
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.128:3306/digital_mall?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
