spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.10.163:3306/digital_mall?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: Zhanjian_123
mybatis:
  mapper-locations: classpath*:com/**/*.xml

